# Generated by Django 5.1.4 on 2025-01-13 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myschoolapp', '0002_rename_name_teacher_first_name_teacher_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10),
        ),
    ]
